name: Run Tests

on: [push, pull_request]

jobs:
  pest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, curl, libxml, sqlite, pdo_sqlite

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
          APP_KEY: base64:fH8VvYh5Z5zD3p9Xl0m7Qz1R2S3T4U5V6W7X8Y9Z0A1=
          WITHOUT_VITE: true
        run: php artisan test --path tests/Feature
